### PR TITLE
Small fix for making Ctrl+Q quitting the app

### PR DESCRIPTION
**Pull request by asafonov**

### CODE REVIEW

**Comment by mammuth** [comment]
It isn't common on Linux or Windows to close an application with ctrl+Q, is it?

**Comment by asafonov** [comment]
@mammuth It's used quite often. Brave is using it, for example.
Anyway, I think it makes more sense than Command+Q ;)

**Comment by diracdeltas** [comment]
++, Brave does this too

**Comment by mammuth** [comment]
Cool 👍

**Pull request merged**
